### ISSUE TITLE
Пути к данным пользователя на сервере

### ISSUE THREAD

**Issue by archer-developer** [ArcherDeveloper228/Server#1]
Путь нужно во-первых вынести в константу, а во-вторых сделать относительным, а не осолютным. 
Вынести в константы для того чтобы убрать дублирование, а относительным так как Вы не можете знать куда пользователь установит сервер и есть ли там вообще диск D например.

**Comment by ArcherDeveloper228** [comment]
Задача решена (24 commit)

**Comment by archer-developer** [comment]
Все равно нужно убрать дублирование - см. комментарий к коммиту

**Comment by ArcherDeveloper228** [comment]
Все поправил(25 commit)

**Comment by ArcherDeveloper228** [comment]
Ну вроде поправил все(26 commit)
