### ISSUE TITLE
Переменные в запросах

### ISSUE THREAD

**Issue by archer-developer** [ArcherDeveloper228/Server#2]
При формировании sql запросов переменные нужно вставлять через prepareStatement. Конструкции вида: 
`"SELECT user_id FROM user WHERE login=\"" + user_login + "\""`
недопустимы так как приводят к [ sql-инъекциям.](https://ru.wikipedia.org/wiki/%D0%92%D0%BD%D0%B5%D0%B4%D1%80%D0%B5%D0%BD%D0%B8%D0%B5_SQL-%D0%BA%D0%BE%D0%B4%D0%B0)

**Comment by ArcherDeveloper228** [comment]
Задача выполнена (23 commit).
